### ISSUE TITLE
Is it possible to intergrate this into QVtkOPenglNativeWidget?

### ISSUE THREAD

**Issue by avilia60** [jspanchu/vtkDearImGUIInjector#2]
I found this amazing project and wonder how i can intergrate it into my person qt5.9-vtk9.2.5 based project,Could you giving me some instructions for doing so?

**Comment by jspanchu** [comment]
Did you try replicating what's done in [test_imgui_vtk.cxx](https://github.com/jspanchu/vtkDearImGUIInjector/blob/main/src/test_imgui_vtk.cxx)?

**Comment by avilia60** [comment]
oh , i have figure it out, thanks for replying.
