### ISSUE TITLE
Can multiple vtkRenderWindow be displayed?

### ISSUE THREAD

**Issue by xjjgjm** [jspanchu/vtkDearImGUIInjector#4]
I need to display 4 vtkRenderWindow, respectively displaying the MPR slice and VR. Using Qt, I only need to put 4 QVTKOpenGLNativeWidgets in the layout and put the vtkRenderWindow inside. I want to know if multiple vtkRenderWindow can be displayed at the same time using **vtkDearImGUIInjector**?

**Comment by jspanchu** [comment]
vktDearImGUIInjector injects the UI elements into a render window, that's it.

This class does not have a notion of layout like the Qt class you're referring to.

**Comment by xjjgjm** [comment]
So, I can only display one vtkRenderWindow at a time?

**Comment by jspanchu** [comment]
Yup. If it helps, You can continue to use Qt to lay out multiple render windows and inject dear Imgui into each of those.

**Comment by xjjgjm** [comment]
OK, thanks
